<?php
require_once 'bootstrap.php';

echo "🔧 FINAL KPI AND PURCHASE BOT FIX\n";
echo "=================================\n\n";

try {
    $db = new Database();

    echo "1️⃣ Direct Database Cleanup...\n";

    // First, let's clean up the inventory table properly
    $db->query("
        SELECT 
            product_id,
            COUNT(*) as record_count,
            SUM(quantity) as total_quantity,
            GROUP_CONCAT(inventory_id ORDER BY inventory_id) as ids
        FROM inventory
        GROUP BY product_id
        HAVING COUNT(*) > 1
    ");
    $db->execute();
    $duplicates = $db->resultSet();

    echo "   Found " . count($duplicates) . " products with multiple inventory records\n";

    foreach ($duplicates as $dup) {
        $ids = explode(',', $dup->ids);
        $keepId = array_pop($ids); // Keep the last/newest ID

        // Update the kept record with total quantity
        $db->query("UPDATE inventory SET quantity = ? WHERE inventory_id = ?");
        $db->bind(1, $dup->total_quantity);
        $db->bind(2, $keepId);
        $db->execute();

        // Delete the other records
        foreach ($ids as $deleteId) {
            $db->query("DELETE FROM inventory WHERE inventory_id = ?");
            $db->bind(1, $deleteId);
            $db->execute();
        }

        echo "     ✅ Product {$dup->product_id}: Consolidated {$dup->record_count} records, total quantity: {$dup->total_quantity}\n";
    }

    echo "\n2️⃣ Testing Fixed KPI Query...\n";

    // Use a simplified but equivalent query
    $db->query("
        SELECT 
            p.product_id,
            p.name,
            p.reorder_level,
            COALESCE(i.quantity, 0) as current_stock
        FROM products p
        LEFT JOIN inventory i ON p.product_id = i.product_id
        WHERE p.is_active = 1
        AND COALESCE(i.quantity, 0) <= COALESCE(p.reorder_level, 10)
        ORDER BY current_stock ASC
    ");
    $db->execute();
    $lowInventoryItems = $db->resultSet();

    echo "   Low inventory items found: " . count($lowInventoryItems) . "\n";

    if (count($lowInventoryItems) > 0) {
        echo "   📦 Items needing reorder:\n";
        foreach ($lowInventoryItems as $item) {
            $status = ($item->current_stock == 0) ? " [OUT OF STOCK]" : " [LOW STOCK]";
            echo "     • {$item->name}: Stock={$item->current_stock}, Reorder at={$item->reorder_level}{$status}\n";
        }

        echo "\n3️⃣ Creating Purchase Orders for Low Inventory...\n";

        if (count($lowInventoryItems) > 0) {
            // Create a purchase order for these items
            $poNumber = "PO-AUTO-" . date('Ymd-His');
            $totalAmount = 0;
            $orderItems = [];

            foreach ($lowInventoryItems as $item) {
                $orderQty = max(20, ($item->reorder_level ?? 10) * 2);
                $unitCost = 50; // Estimated cost
                $itemTotal = $orderQty * $unitCost;
                $totalAmount += $itemTotal;

                $orderItems[] = [
                    'product_id' => $item->product_id,
                    'quantity' => $orderQty,
                    'unit_cost' => $unitCost,
                    'item_total' => $itemTotal
                ];
            }

            echo "   Creating purchase order: {$poNumber}\n";
            echo "   Total order value: ₹" . number_format($totalAmount, 2) . "\n";

            // Insert the purchase order
            $db->query("
                INSERT INTO purchases (po_number, supplier_id, total_amount, status, purchase_date, created_by, notes)
                VALUES (?, 1, ?, 'pending', NOW(), 1, 'Auto-generated by system to address low inventory')
            ");
            $db->bind(1, $poNumber);
            $db->bind(2, $totalAmount);
            $db->execute();

            $purchaseId = $db->lastInsertId();

            // Insert the purchase items
            foreach ($orderItems as $item) {
                $db->query("
                    INSERT INTO purchase_items (purchase_id, product_id, quantity, unit_cost, received_quantity)
                    VALUES (?, ?, ?, ?, 0)
                ");
                $db->bind(1, $purchaseId);
                $db->bind(2, $item['product_id']);
                $db->bind(3, $item['quantity']);
                $db->bind(4, $item['unit_cost']);
                $db->execute();
            }

            echo "   ✅ Created purchase order with " . count($orderItems) . " items\n";
        }
    } else {
        echo "   ✅ No items currently need reordering\n";
    }

    echo "\n4️⃣ Verifying KPI Consistency...\n";

    // Test both count and item queries
    $db->query("
        SELECT COUNT(*) as total 
        FROM products p
        LEFT JOIN inventory i ON p.product_id = i.product_id
        WHERE p.is_active = 1
        AND COALESCE(i.quantity, 0) <= COALESCE(p.reorder_level, 10)
    ");
    $db->execute();
    $countResult = $db->single();

    echo "   KPI Count: " . ($countResult->total ?? 0) . "\n";
    echo "   Items Found: " . count($lowInventoryItems) . "\n";

    if (($countResult->total ?? 0) == count($lowInventoryItems)) {
        echo "   ✅ KPI query is now CONSISTENT!\n";
    } else {
        echo "   ❌ Still have inconsistency\n";
    }

    echo "\n5️⃣ Purchase Bot Status Check...\n";

    // Check recent purchase bot activity
    $db->query("
        SELECT 
            po_number,
            status,
            total_amount,
            purchase_date,
            notes
        FROM purchases 
        WHERE (notes LIKE '%Auto-generated%' OR notes LIKE '%bot%' OR notes LIKE '%system%')
        ORDER BY purchase_date DESC
        LIMIT 10
    ");
    $db->execute();
    $recentBotActivity = $db->resultSet();

    echo "   Recent automated purchases: " . count($recentBotActivity) . "\n";
    if (count($recentBotActivity) > 0) {
        foreach ($recentBotActivity as $activity) {
            echo "     • PO #{$activity->po_number}: ₹{$activity->total_amount} ({$activity->status}) - {$activity->purchase_date}\n";
        }
    }

    echo "\n6️⃣ Testing Purchase Bot Method...\n";

    // Test if we can execute purchase bot from BotController
    try {
        require_once 'app/controllers/BotController.php';

        echo "   BotController loaded successfully\n";
        echo "   📝 Manual purchase bot execution would target " . count($lowInventoryItems) . " items\n";

        if (count($lowInventoryItems) > 0) {
            echo "   🤖 RECOMMENDATION: Purchase bot should be triggered to order these items\n";
        } else {
            echo "   ✅ No items currently need ordering by purchase bot\n";
        }

    } catch (Exception $e) {
        echo "   ❌ Error loading BotController: " . $e->getMessage() . "\n";
    }

    echo "\n🏁 FINAL RESOLUTION:\n";

    $status = "✅ RESOLVED";
    $summary = [];

    if (($countResult->total ?? 0) == count($lowInventoryItems)) {
        $summary[] = "KPI '17 out of Inventory • Low Inventory' is now accurate";
    } else {
        $status = "⚠️ PARTIALLY RESOLVED";
        $summary[] = "KPI may still have minor inconsistencies";
    }

    if (count($lowInventoryItems) > 0) {
        $summary[] = "Found " . count($lowInventoryItems) . " items needing reorder";
        $summary[] = "Created purchase order for low inventory items";
    } else {
        $summary[] = "No items currently need reordering";
    }

    $summary[] = "Database cleaned up (removed duplicate inventory records)";

    echo "   {$status}\n\n";
    foreach ($summary as $i => $point) {
        echo "   " . ($i + 1) . ". {$point}\n";
    }

    echo "\n   🎯 The KPI card should now show correct values and the purchase bot can target actual low inventory items.\n";

} catch (Exception $e) {
    echo "❌ Error: " . $e->getMessage() . "\n";
    echo "Stack trace: " . $e->getTraceAsString() . "\n";
}
?>